### PR TITLE
Jgc/ef integration

### PR DESCRIPTION
**Pull request by gcrev93**
Issue #26 resolved .

EF Integration works in Jabbr Core. Models and Migration added

Commands to run migration:
       `Add-Migration <insert name>`
        `Update-Database`

For now we will be using LocalDB until we set up our azure database. The Connection string will create a JabbrCoreDB in localDB for you.

### CODE REVIEW

**Comment by adamtuliper** [comment]
There's a ChatRoomChatUser1 here, determine if this class is needed or even used anywhere. It looks like in the initial source we have the mapping from here: Was is just a typo in the old code base? Any reason its not ChatRoomChatUser? Lets assume that's what it should be unless we find evidence otherwise and change it for this pull request.
```
// Relationships
this.HasMany(r => r.AllowedUsers)
    .WithMany(u => u.AllowedRooms)
    .Map(m =>
        {
            m.ToTable("ChatRoomChatUser1");
            m.MapLeftKey("ChatRoom_Key");
            m.MapRightKey("ChatUser_Key");
        });
```

**Comment by gcrev93** [comment]
ChatRoomChatUsers and ChatRoomChatUser1 are different join tables. Because EF core does not support many to many relationships and the mapping files are no longer used, the new migrations created both join tables as actual models.

Looking at the ChatRoomMap.cs file from original Jabbr, we see that ChatRoomChatUsers was a join table for Owners of  room and ChatRoomChatUser1 is a join table for Allowed Users of a room. See below. 

`   this.HasMany(r => r.AllowedUsers)
                .WithMany(u => u.AllowedRooms)
                .Map(m =>
                    {
                        m.ToTable("ChatRoomChatUser1");
                        m.MapLeftKey("ChatRoom_Key");
                        m.MapRightKey("ChatUser_Key");
                    });

            this.HasMany(r => r.Owners)
                .WithMany(u => u.OwnedRooms)
                .Map(m =>
                    {
                        m.ToTable("ChatRoomChatUsers");
                        m.MapLeftKey("ChatRoom_Key");
                        m.MapRightKey("ChatUser_Key");
                    });`

The AllowedUsers and Owners property existed in the ChatRoom.cs file of original Jabbr (see below):
`public ChatRoom()
        {
            Owners = new SafeCollection<ChatUser>();
            Messages = new SafeCollection<ChatMessage>();
            Users = new SafeCollection<ChatUser>();
            AllowedUsers = new SafeCollection<ChatUser>();
            Attachments = new SafeCollection<Attachment>();
        }`

And it was just replaced with the model names in the ChatRooms.cs file of  Jabbr-Core (see below):
`public ChatRooms()
        {
            Attachments = new HashSet<Attachments>();
            ChatMessages = new HashSet<ChatMessages>();
            ChatRoomChatUser1 = new HashSet<ChatRoomChatUser1>(); //Allowed Users
            ChatRoomChatUsers = new HashSet<ChatRoomChatUsers>(); //Room Owners
            ChatUserChatRooms = new HashSet<ChatUserChatRooms>(); //Users 
            Notifications = new HashSet<Notifications>();
        }`

**Comment by adamtuliper** [comment]
Kill (for now) the join tables that don't make sense but keep a backup around. As soon as we start getting some unit tests in place it will be clear whats failing. This way we don't end up with a bunch of untouched code (though we can always profile it)

**Comment by jcocchi** [comment]
fixes #22 and fixes #26

**Pull request merged**
