### PR TITLE
Settings view

### PR DESCRIPTION
**Pull request by gcrev93**
Added Account settings controller and view

### CODE REVIEW

**Comment by adamtuliper** [comment]
See email re this (ex Controllers folder)

**Comment by gcrev93** [comment]
updated the folder

**Comment by gcrev93** [comment]
All that needs to be is done is run the code and be sure the functions in the Account Controller work. To test just go to url/account/testfunction.

**Comment by gcrev93** [comment]
Also a lot of functionality is commented out due to hard coded data but the pages should return something at all times, just look at the return values of each function.

**Comment by KSLHacks** [comment]
Testing all Account Controllers/Views on settingsView branch:

Testing all [HttpGet]
- [x] /account/ yields account/index
- [x] /account/login
- [x] /account/register
- [x] /account/RequestResetPassword
- [x] /account/ResetPassword

We were able to step into the [HttpPost] methods using Fiddler by specifying:
`Content-Type: application/x-www-form-urlencoded`, and adding to the Request body.
Since there is no functionality with user data I just ensured the views worked and did not test the logic.

*Note we may need to specify urlencoded for unit tests in the future
`[InlineData("application/x-www-form-urlencoded")]`

:shipit:

**Pull request merged**
