### PR TITLE
Partial html templates

### PR DESCRIPTION
**Pull request by JamesEarle**
I moved html pieces into separate files for cleaner code.

### CODE REVIEW

**Comment by JamesEarle** [comment]
👍

**Comment by jcocchi** [comment]
👍

**Comment by KSLHacks** [comment]
:+1:

**Comment by adamtuliper** [comment]
cool - good to see how they are broken out.

What are paths where these are rendered from? Are they reused across
various controllers?

Lets layout controller scheme here to determine if these are necessary and
any reuse is required, others we may use just a regular view or even
template to use via angular with binding. I'm hesitant on partials if they
are just jquery templates that will now become angular template views, we
may want to consider diff architecture.

**Comment by gcrev93** [comment]
Checked it in! Thanks James

**Comment by JamesEarle** [comment]
All of the jQuery templates used to be in between the `<head></head>` tags of `index.cshtml`, but it took up over half the document and was pretty hard to read through.

It looks like they're loaded in `<script></script>` tags at the beginning of the file, and then those scripts are called on demand from more JavaScript as the templates are needed (new user, new room, etc), so it is definitely feasible that we move that logic to the controllers I think. 

We could always rearchtiect with Angular later but this was also a simple example of branching, pull requests, etc. that I wanted to do to go over some of the workflow

**Comment by adamtuliper** [comment]
Understood (though region collapsing makes this minimal) and moving it is a
great idea.
This is a common pattern for templates such as jquery-tmpl, angular, ember,
etc. They look for those templates in script tags.
It makes sense to move them _somewhere_ - lets figure out a good first
location for them before this is submitted (as it requires other code
changes like Html.Partial) as a static file with cache busting url may work
and preferable over a partial view scenario (any time we can avoid server
pipeline and use hot cache is preferable)
Lets chat this week. This is all live code for us now once merged, one
change affects everyone :)

**Pull request merged**
