### PR TITLE
Gabby/AddOwnerCommand

### PR DESCRIPTION
**Pull request by gcrev93**
The  Add Owner command is used in the chatroom to make a Jabbr user an Owner of that room.. To test you should be able to click into light meow and in the textbox type /addowner [username] and it should return "[username] is now an owner of light_meow". If you put a username that does not exist, it should return " Unable to find [username]"

### CODE REVIEW

**Comment by adamtuliper** [comment]
Is this ready for testing? Needs to be tested before we can merge :)

**Comment by KSLHacks** [comment]
Tested UI:
- [x] entered room
- [x] "/addowner Jack" -> "Jack is now an owner of light_meow"
- [x] "/addowner Jane" -> "Jane is now an owner of light_meow"
- [x] "/addowner Adam" -> HubException Hit -> UI prints to chat "Unable to find Adam"

I was able to run back to back "/addowner Jack" with the same results. Should this be able to repeatedly do? I know we don't have real data. If this is expected, then :shipit:

**Comment by ashanhol** [comment]
This totally does what gabby says and adds the user as a room owner. Owners are not added to database so you can add a person as an owner more than once, which shouldn't happen once we actually get the database and caching to work. :shipit:

**Comment by JamesEarle** [comment]
@ashanhol @gcrev93 why are you able to add the Owner more than once? Even using the InMemoryRepository it should still be able to detect the user already exists as an owner right?

**Comment by adamtuliper** [comment]
Can you verify old Jabbr behavior here? Looking at the schema real quick, looks like this is enforced by referential integrity in the database, which is fine, but also enforced in the command. Be nice to verify what happens in the old Jabbr as far as error message though. The repository shouldn't check this, but the AddOwner command should. Looking at the old code, it looks like it does? See "  // If the target user is already an owner, then throw"
```
//this single line of code from AddOwnerCommand.cs
context.Service.AddOwner(callingUser, targetUser, targetRoom);
..
//ChatService.cs
public void AddOwner(ChatUser ownerOrCreator, ChatUser targetUser, ChatRoom targetRoom)
{
    // Ensure the user is owner of the target room
    EnsureOwnerOrAdmin(ownerOrCreator, targetRoom);

    if (targetRoom.Owners.Contains(targetUser))
    {
        // If the target user is already an owner, then throw
        throw new HubException(String.Format(LanguageResources.RoomUserAlreadyOwner, targetUser.Name, targetRoom.Name));
    }

    // Make the user an owner
    targetRoom.Owners.Add(targetUser);
    targetUser.OwnedRooms.Add(targetRoom);

    if (targetRoom.Private)
    {
        if (!targetRoom.AllowedUsers.Contains(targetUser))
        {
            // If the room is private make this user allowed
            targetRoom.AllowedUsers.Add(targetUser);
            targetUser.AllowedRooms.Add(targetRoom);
        }
    }
}
```

**Comment by gcrev93** [comment]
So I looked into running it twice and it should give an error that the person is already an owner. But if its hardcoded in the InMemoryRepo, then will it ever really show the change? Changes we make on the site arent actually saved to the InMemoryRepo.. so we wouldnt see that error correct?

**Pull request merged**
