### PR TITLE
Brought over NoteComand

### PR DESCRIPTION
**Pull request by ashanhol**
To test: 
So we're having a more general problem with things not displaying in the chatroom, but the note is being changed. If you set a breakpoint in NoteCommand to see if       `context.NotificationService.ChangeNote(callingUser);` runs, you can see that it updates the callingUser's note if you run /note. (running /note with no perams will clear the note).

### CODE REVIEW

**Comment by ashanhol** [comment]
Update: This should totally work now. If you type /note "string" it should pop up grey with a message that says "Your note has been set to 'string'.", and appear if you hover over your name in the sidebar with owners/users.

**Comment by gcrev93** [comment]
So what i noticed is:

I already had a room created from previous test and when i just enter the room, this command does not work

If i make a new chat room and then try the command , it does work! is that right?

**Comment by adamtuliper** [comment]
@ashanhol where do we stand with this?

**Comment by KSLHacks** [comment]
@ashanhol This command seems to work
- Able to set the note
- Note shows when you hover mouse over user
- Note shows in the Account page
- Able to delete the note
- Able to add another note and shows appropriately

The only bug is when you delete your current note, It prints in the chat that your note is cleared x2.

**Comment by KSLHacks** [comment]
Testing pending @adamtuliper's context changes.

**Pull request merged**
