### PR TITLE
Account controller integration

### PR DESCRIPTION
**Pull request by jcocchi**
Use Cases to Test:
 - Register a new user
 - Create a room and send a message in that room
 - Log out (you might have to restart the project to avoid the self-referencing loop error in issues #126 and #129)
 - Log the user back in and check to make sure you can see the old messages in the room
 - Change the user's name and password
 - Log out
 - Log back in with the new name and password
 - Log out
 - Log back in one more time but this time say you "forgot your password"
 - Verify you got an email with a new password and can log in
 - Log out
 - Register a new user using Google authentication
 - Register a new user using Facebook authentication

Try to enter invalid entries in each form and verify all validation messages are working properly. 
Register a couple users and verify old messages from other users display in the room.

### CODE REVIEW

**Comment by ashanhol** [comment]
- I'm having trouble creating a new room if I've already visited a room. It'll throw "An exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code" at line 280 in PersistedRepository.cs. 
- Still having issues with Login. Throws an exception when I try to log in with (or without) a user in the database. ViewModel exception.

**Comment by gcrev93** [comment]
- I noticed that I am having login issues. Gives me the LoginViewModel error
- In the nav bar the help and logout buttons do not execute but notifications and account do?

**Comment by gcrev93** [comment]
Just retested and Login works :)
Looking into the nav bar now

**Comment by KSLHacks** [comment]
- Login Works (with already registered user credentials)
- Authorization routing works with AccountController (excluding HomeController)
- Able to Logoff
- Able to re-login

**Comment by ashanhol** [comment]
Facebook login works, normal login works, login/logout works (except the logout button in Account?), messages persist across logins. 
Things that do not work: 
- issue #267, 
- forgot password- see below,
- google authentication authenticates but throws an exception if you try to join a room with nullreferencexception in UserViewModel with the User's name. This doesn't happen with FB- probably b/c it has you create a username after you register while google does not. 

Forgot password error: 
`An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

Generated Code

Type expected
        #pragma warning restore 1998
Type expected
        #pragma warning restore 1998
Type expected
        #pragma warning restore 1998
The type or namespace name 'ForgotPasswordViewModel' could not be found (are you missing a using directive or an assembly reference?)
    public class _Views_Account_ForgotPassword_cshtml : Microsoft.AspNetCore.Mvc.Razor.RazorPage<ForgotPasswordViewModel>
The type or namespace name 'ForgotPasswordViewModel' could not be found (are you missing a using directive or an assembly reference?)
        public Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<ForgotPasswordViewModel> Html { get; private set; }
The type or namespace name 'ForgotPasswordViewModel' could not be found (are you missing a using directive or an assembly reference?)
        #pragma warning restore 1998
The type or namespace name 'ForgotPasswordViewModel' could not be found (are you missing a using directive or an assembly reference?)
        #pragma warning restore 1998
The type or namespace name 'ForgotPasswordViewModel' could not be found (are you missing a using directive or an assembly reference?)
        #pragma warning restore 1998

/Views/Account/ForgotPassword.cshtml

The type or namespace name 'Jabbr_Core' could not be found (are you missing a using directive or an assembly reference?)
@using Jabbr_Core.ViewModels;
`

**Comment by heatherbshapiro** [comment]
updated forgotpassword.cshtml so the link should be working now for forgot password.

**Comment by KSLHacks** [comment]
Refactored ForgotPassword.cshrml and ForgotPasswordComfirmation.cshtml to match layout. UI changes.

**Comment by ashanhol** [comment]
Ok. Then only issue #267 remains but can be dealt with after. Seems like things work!!!!! O_O
:shipit:

**Comment by KSLHacks** [comment]
I only see issues #267 and #129 which can be addressed in 0.6
:Shipit:

**Pull request merged**
