### PR TITLE
Gabby/notification view

### PR DESCRIPTION
**Pull request by gcrev93**
Added Notifcation View and controller.

### CODE REVIEW

**Comment by adamtuliper** [comment]
Change controller locations to /Controllers and commit again. thanks!

**Comment by gcrev93** [comment]
Controllers location fixed

**Comment by gcrev93** [comment]
All that needs to be is done is run the code and be sure the functions in the Notifications Controller work. To test just go to url/notifcation/testfunction

**Comment by gcrev93** [comment]
Also a lot of functionality is commented out due to hard coded data but the pages should return something at all times, just look at the return values of each function.

**Pull request closed without merging**
