### PR TITLE
Adina/where command

### PR DESCRIPTION
**Pull request by ashanhol**
To test: 
The command is /where "user"- it should list the user and the rooms its in. There was a bit of a delay before it popped up in the room itself.

### CODE REVIEW

**Comment by KSLHacks** [comment]
Testing Results:
- [x] Testing command with no argument
"/where" -> "Who do you want to locate?"

- [x] Testing command with invalid user
"/where RandomUser" -> "Unable to find RandomUser"

- [ ] Testing command with my current logged in username
"/where Kevin" -> "Kevin (Currently null) is in the follow rooms: testRoom"

Do we know why the current user is null and why this is printing?

**Comment by ashanhol** [comment]
@KSLHacks that's so weird, it's not saying the user's null it's printing whether users active or afk. In Jabbr20 it prints "adinas (Currently Active) is in the following rooms:". If you look at the user isafk value it should be set to false because UpdateActivity() keeps setting it to false.

**Comment by ashanhol** [comment]
@KSLHacks Update: So it looks like regardless of what the status is for the user, it's always getting passed in as null by the hub into chat.js. I hardcoded the value as Active for now so something displays for now- but I think this might be a SignalR problem.

**Comment by adamtuliper** [comment]
Go ahead and create a new issue to track this item with all the details re the failing case above and the force-active coe you had to do. Once you do, merge this and close/delete branch.

**Pull request merged**
