### PR TITLE
Brought over Identity Nuget, startup.cs, DI into AccountController.cs

### LINKED ISSUE #173: NuGet Packages for identity and configure startup.cs options
Configure cookie authentication
Look at a new web project for example configuration of startup class
https://docs.asp.net/en/latest/security/authentication/identity.html

### PR DESCRIPTION
**Pull request by KSLHacks**
Closes #173. 
- [x] Nuget
- [x] Startup.cs config and services added
- [x] Set up DI into AccountController.cs

### CODE REVIEW

**Comment by KSLHacks** [comment]
@jcocchi Refactored user.Keys to implement user.Id (string) so we only have one primary key to worry about. Investigated that we do not leak the user.Id to the client. Updated EF Migrations.

**Testing**
1. 'SQL Server Object Explorer' > (localdb)\MSSQLLocalDB > Databases > Delete JabbrDB & JabbrDBTests
2. In Project Manager console, target Default Project 'src\JabbR-Core.Data' and run 'update-database'
3. Build and run project - should be able to compile and do basic SignalR connetion/chatroom commands

**Comment by adamtuliper** [comment]
In the first step above "Make sure your target package is JabbR-Core.Data" whats pointing to the database to update at this point?

**Comment by jcocchi** [comment]
@adamtuliper It uses the DB configuration set up in the startup class, the connection string needs to be stored as a user secret on your local machine. If it isn't already set up then you can follow the instructions at the beginning of the ConfigureServices method

**Comment by heatherbshapiro** [comment]
I had to switch the connection string in the first step, not the second but it works after that :). 

All of the tests pass :) 

The site works with this line uncommented `string connection = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=JabbREFTest;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"; `

**Comment by heatherbshapiro** [comment]
:shipit:

**Comment by jcocchi** [comment]
@heatherbshapiro It won't work with `string connection = _configuration["connectionString"];` uncommented unless you set up the connection string as an environment variable on your local machine. There are instructions for that at the beginning of the ConfigureServices method in the startup class

**Comment by adamtuliper** [comment]
@jcocchi we should consider adding specific steps into Readme.md for "local setup" including environment variable.

**Pull request merged**
